"use client";

import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { FileBarChart, Search, Plus, Activity, Eye, Download, Trash2 } from 'lucide-react';
import Table from '../../components/common/Table';
import HeroSection from '../../components/orderreport/HeroSection';
import { toast } from 'react-hot-toast';

const OrderReportPage = () => {
    const navigate = useNavigate();
    const [searchText, setSearchText] = useState("");
    const columns = [
        { header: "Report ID", accessor: "reportId" },
        { header: "Report Type", accessor: "reportType" },
        { header: "Period", accessor: "period" },
        { header: "Generated By", accessor: "generatedBy" },
        { header: "Date Generated", accessor: "dateGenerated" },
        {
            header: "Status",
            accessor: "status",
            render: (row) => (
                <span className={`px-2.5 py-1 rounded-full text-xs font-bold uppercase tracking-wide ${row.status === 'Completed' ? 'bg-green-100 text-green-700' :
                        row.status === 'Pending' ? 'bg-yellow-100 text-yellow-700' : 'bg-red-100 text-red-700'
                    }`}>
                    {row.status}
                </span>
            )
        },
    ];

    // Mock data for Order Reports
    const [orderReports, setOrderReports] = useState([
        { id: 1, reportId: "ORD-REP-001", reportType: "Monthly Sales", period: "July 2024", generatedBy: "Admin John", dateGenerated: "2024-08-01", status: "Completed" },
        { id: 2, reportId: "ORD-REP-002", reportType: "Daily Transactions", period: "2024-07-22", generatedBy: "Admin Jane", dateGenerated: "2024-07-22", status: "Completed" },
        { id: 3, reportId: "ORD-REP-003", reportType: "Product Performance", period: "Q2 2024", generatedBy: "Admin John", dateGenerated: "2024-07-10", status: "Pending" },
    ]);

    const filteredOrderReports = orderReports.filter(report =>
        report.reportId.toLowerCase().includes(searchText.toLowerCase()) ||
        report.reportType.toLowerCase().includes(searchText.toLowerCase()) ||
        report.generatedBy.toLowerCase().includes(searchText.toLowerCase())
    );

    const handleDelete = (id) => {
        if (window.confirm("Are you sure you want to delete this report?")) {
            setOrderReports(orderReports.filter(report => report.id !== id));
            toast.success('Report deleted successfully!');
        }
    };

    const handleView = (id) => {
        console.log(`Viewing report ${id}`);
        toast.info(`Viewing report ${id} (functionality to be implemented)`);
    };

    const handleDownload = (id) => {
        console.log(`Downloading report ${id}`);
        toast.success(`Downloading report ${id}...`);
    };

    return (
        <div className="animate-in fade-in slide-in-from-bottom-4 duration-500 pb-12">
            <HeroSection />

            {/* STATUS LEGEND */}
            <div className="mt-8 mb-4">
                <div className="bg-white rounded-2xl border border-gray-100 p-4 shadow-sm flex flex-col md:flex-row items-start md:items-center justify-between gap-4">
                    <div className="flex items-center gap-3">
                        <Activity className="h-5 w-5 text-indigo-600" />
                        <span className="text-sm font-bold text-gray-700 uppercase tracking-wide">Report Status:</span>
                    </div>
                    <div className="flex flex-wrap gap-4 text-xs font-medium text-gray-600">
                        <div className="flex items-center gap-2">
                            <span className="w-2 h-2 rounded-full bg-green-500" />
                            <span className="bg-green-100 text-green-700 px-2 py-0.5 rounded font-bold">COMPLETED</span>
                            <span>- Report generated successfully</span>
                        </div>
                        <div className="flex items-center gap-2">
                            <span className="w-2 h-2 rounded-full bg-yellow-500" />
                            <span className="bg-yellow-100 text-yellow-700 px-2 py-0.5 rounded font-bold">PENDING</span>
                            <span>- Generation in progress</span>
                        </div>
                        <div className="flex items-center gap-2">
                            <span className="w-2 h-2 rounded-full bg-red-500" />
                            <span className="bg-red-100 text-red-700 px-2 py-0.5 rounded font-bold">FAILED</span>
                            <span>- Report generation failed</span>
                        </div>
                    </div>
                </div>
            </div>

            {/* SEARCH & FILTER CARD */}
            <div className="bg-white rounded-[2rem] border border-gray-100 shadow-sm p-8 mb-8">
                <div className="flex flex-col md:flex-row md:items-center justify-between mb-8 gap-4">
                    <h2 className="text-xl font-bold text-gray-900 tracking-tight">Generated Reports</h2>
                    <button
                        onClick={() => navigate('/order-report/generate')}
                        className="flex items-center gap-2 px-6 py-2.5 bg-indigo-600 text-white font-bold rounded-xl shadow-lg shadow-indigo-200 hover:bg-indigo-700 transition-all active:scale-95"
                    >
                        <Plus className="h-5 w-5" />
                        Generate New Report
                    </button>
                </div>
                <div className="relative">
                    <Search className="absolute left-4 top-1/2 -translate-y-1/2 h-4 w-4 text-gray-400" />
                    <input
                        type="text"
                        placeholder="Search reports..."
                        className="w-full pl-11 pr-4 py-3 bg-gray-50 border border-gray-100 rounded-xl text-sm font-medium focus:outline-none focus:ring-2 focus:ring-indigo-100 focus:border-indigo-200 transition-all"
                        value={searchText}
                        onChange={(e) => setSearchText(e.target.value)}
                    />
                </div>
            </div>

            {/* TABLE */}
            <div className="bg-white rounded-[2rem] border border-gray-100 shadow-sm p-8 overflow-hidden">
                <Table
                    title=""
                    columns={columns}
                    data={filteredOrderReports}
                    actions={(row) => (
                        <div className="flex gap-2">
                            <button
                                onClick={() => handleView(row.id)}
                                className="p-2 text-indigo-600 hover:bg-indigo-50 rounded-lg transition-colors"
                                title="View"
                            >
                                <Eye className="h-4 w-4" />
                            </button>
                            <button
                                onClick={() => handleDownload(row.id)}
                                className="p-2 text-green-600 hover:bg-green-50 rounded-lg transition-colors"
                                title="Download"
                            >
                                <Download className="h-4 w-4" />
                            </button>
                            <button
                                onClick={() => handleDelete(row.id)}
                                className="p-2 text-red-500 hover:bg-red-50 rounded-lg transition-colors"
                                title="Delete"
                            >
                                <Trash2 className="h-4 w-4" />
                            </button>
                        </div>
                    )}
                />
                {filteredOrderReports.length === 0 && (
                    <div className="text-center py-12 text-gray-400 text-sm italic">
                        No order reports found.
                    </div>
                )}
            </div>
        </div>
    );
};
export default OrderReportPage;